camel:
  component:
    aws-sqs:
      region: SA_EAST_1
    servlet:
      mapping:
        contextPath: /zup/*
auto.offset.reset: earliest

aws:
  dynamodb:
    endpoint: http://localhost:8000/
  accesskey: fakekey
  secretkey: fakesecret


payments:
  sqs:
    url: https://sqs.sa-east-1.amazonaws.com/499137437067/ted-sqs-queue
    accesskey: AKIAXINXI3WFZEYFI3HQ
    secretkey: pyMW2dIUeFHathfsWlwJqyOxsemK5Mm3htinSCds
    queue:
      ted: ted-sqs-queue
      doc: doc-sqs-queue
      pix: pix-sqs-queue
  kafka:
    host: localhost
    port: 9092
    kafka-broker: kafka:%s?brokers=${payments.kafka.host}:${payments.kafka.port}
    channel: 8
    ted-included:
      topic-name: payments-ted

